#!/usr/bin/env node

import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      resolve(answer);
    });
  });
}

async function main() {
  console.log('\n🚀 Linode Manager Setup\n');
  console.log('This script will help you configure your Linode API credentials.\n');
  console.log('You can get your Linode API token from:');
  console.log('https://cloud.linode.com/profile/tokens\n');
  console.log('Required scopes: Linodes (Read/Write), Images (Read), Regions (Read)\n');

  const token = await question('Enter your Linode API Token: ');

  if (!token.trim()) {
    console.error('\n❌ Error: API token is required.\n');
    process.exit(1);
  }

  // Validate the token by making a test API call
  console.log('\n🔍 Validating API token...');
  
  try {
    const response = await fetch('https://api.linode.com/v4/profile', {
      headers: {
        'Authorization': `Bearer ${token.trim()}`
      }
    });

    if (!response.ok) {
      throw new Error(`API returned ${response.status}`);
    }

    const profile = await response.json();
    console.log(`✅ Token valid! Authenticated as: ${profile.email || profile.username}\n`);
  } catch (error) {
    console.error(`\n❌ Error: Invalid API token or network issue: ${error.message}\n`);
    process.exit(1);
  }

  // Create .env file
  const envPath = path.join(projectRoot, '.env');
  const envContent = `# Linode Manager Configuration
# Generated by setup script

# Linode API Token
# Get yours at: https://cloud.linode.com/profile/tokens
LINODE_API_TOKEN=${token.trim()}
`;

  fs.writeFileSync(envPath, envContent);
  console.log(`✅ Configuration saved to ${envPath}\n`);

  // Check if .env is in .gitignore
  const gitignorePath = path.join(projectRoot, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const gitignore = fs.readFileSync(gitignorePath, 'utf-8');
    if (!gitignore.includes('.env')) {
      console.log('⚠️  Warning: .env is not in .gitignore. Adding it now...');
      fs.appendFileSync(gitignorePath, '\n.env\n');
      console.log('✅ Added .env to .gitignore\n');
    }
  }

  console.log('🎉 Setup complete!\n');
  console.log('Next steps:');
  console.log('  1. Run: npm install');
  console.log('  2. Run: npm run dev');
  console.log('  3. Open: http://localhost:3000\n');

  rl.close();
}

main().catch((error) => {
  console.error('Setup failed:', error);
  rl.close();
  process.exit(1);
});
